version: '3.8'

services:
  #shop:
  #  build: /shop
  #  container_name: shop
  #  ports:
  #    - 8080:80

  db:
    image: mongo
    container_name: db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=admin
    volumes:
      - data:/data
    ports:
      - "27017:27017"

  db-admin:
    image: mongo-express
    container_name: db_admin
    restart: always
    ports:
      - "8080:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=admin
      - ME_CONFIG_MONGODB_SERVER=db
      - ME_CONFIG_MONGODB_URL="mongodb://root:admin@db:27017"

volumes:
  data: {}

networks:
  default:
    name: mongodb_network 